apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: capstone-pod
        image: udacity1project/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  type: LoadBalancer
  selector:
    app: blue
  ports:
  - port: 80
    targetPort: 80